version: '3.5'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2017-CU14-ubuntu
    container_name: my_database
    environment:
      SA_PASSWORD: Tel1234!
      ACCEPT_EULA: Y
    volumes:
      - ./data:/scripts/
    command:
      - /bin/bash
      - -c
      - |
        # Launch MSSQL and send to background
        /opt/mssql/bin/sqlservr &

        sleep 30

        # https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/connecting-with-bcp?view=sql-server-ver15
        # https://docs.microsoft.com/en-us/sql/tools/bcp-utility?redirectedfrom=MSDN&view=sql-server-ver15
        # /opt/mssql-tools/bin/sqlcmd -l 30 -S localhost -h-1 -V1 -U sa -P $$SA_PASSWORD -Q "SET NOCOUNT ON SELECT \"Database Available\" , @@servername"

        # Run every script in /scripts
        # Set a flag so that this is only done once on creation,
        # and not every time the container runs
        for foo in /scripts/*.sql
          do /opt/mssql-tools/bin/sqlcmd -U sa -P $$SA_PASSWORD -i $$foo
        done

        # So that the container doesn't shut down, sleep this thread
        sleep infinity
    ports:
      - 1150:1433
    networks:
      - mynetwork
  backend:
    build: backend/
    image: backend:1.0
    container_name: backend
    ports:
      - 1151:80
    depends_on:
      - database
    networks:
      - mynetwork
  frontend:
    build: frontend/
    image: frontend:1.0
    container_name: frontend
    ports:
      - 1152:80
    depends_on:
      - backend
    networks:
      - mynetwork
networks:
  mynetwork:
    name: pos_workshop
    driver: bridge

